### ISSUE TITLE
Error trying to run plugin

### ISSUE THREAD

**Issue by VocAddict** [FireController1847/musescore-rich-presence#2]
I tried to run the plugin after it was enabled but I don't get the option in the dropdown. I'm not sure what's causing it.

Plugin Manager
![image](https://user-images.githubusercontent.com/7100190/111075570-04423580-84bf-11eb-8ac0-d1e41c133ed0.png)

Plugin Menu
![image](https://user-images.githubusercontent.com/7100190/111075582-102df780-84bf-11eb-80e9-d734a975a530.png)

**Comment by FireController1847** [comment]
Unfortunately I no longer maintain this plugin so I'm not entirely sure what could be going on. If you'd like to take a look at the source and/or are able to, all PRs are appreciated! :)

**Comment by FireController1847** [comment]
This has been fixed in the latest commit.
