### ISSUE TITLE
Current Score Info for MS3 doesn't work

### ISSUE THREAD

**Issue by BlueAcidball** [FireController1847/musescore-rich-presence#5]
I installed the plugin, enabled it on Plugin Manager, and clicked on "Start Current Score Info" under the Plugins tab. But nothing happened, and I tried clicking again and again, but it was the same result. When I ran rpc.js, sure enough, it said, "Whoops! I wasn't able to find the ScoreInfo.json. Did you install the CurrentScoreInfo MuseScore plugin?" even though I did install the plugin.

**Comment by FireController1847** [comment]
Make sure to run MuseScore as an administrator, otherwise it doesn't have permission to create the file
