### ISSUE TITLE
im a beginner in this stuff

### ISSUE THREAD

**Issue by AlinKaslana** [FireController1847/musescore-rich-presence#9]
how to clone repository and install the node module? im confused with it

**Comment by FireController1847** [comment]
how to clone a github repo: https://www.youtube.com/watch?v=q9wc7hUrW8U
how to install node.js: https://www.youtube.com/watch?v=06X51c6WHsQ

once you have node.js installed you just need to open a command prompt in the repository's folder and run `npm install`

cli nativation: https://www.youtube.com/watch?v=8-mYKkNzjU4

this is the most support i can provide to you; i would recommend looking around YouTube if you need further help
